apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 2  # Número de réplicas que você deseja rodar
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: lfpicoloto/my-app:latest  
        ports:
        - containerPort: 8000  
        env:
        - name: CLOUD_TOKEN  
          value: $(CLOUD_TOKEN)
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 8000 
  type: LoadBalancer 
