name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t my-app:$GITHUB_SHA .

    - name: Run tests
      run: |
        docker run --rm my-app:$GITHUB_SHA pytest

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker tag my-app:$GITHUB_SHA my-docker-repo/docs-guard:$GITHUB_SHA
        docker push my-docker-repo/docs-guard:$GITHUB_SHA
