name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t my-app:$GITHUB_SHA .

      - name: Create pytest.ini
        run: |
          echo "[pytest]" > pytest.ini
          echo "asyncio_mode = auto" >> pytest.ini
          echo "asyncio_default_fixture_loop_scope = function" >> pytest.ini

      - name: Run tests
        run: |
          docker run --rm -v ${{ github.workspace }}/pytest.ini:/app/pytest.ini my-app:$GITHUB_SHA pytest -v
